# Generated by Django 3.1.1 on 2020-09-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.CharField(default='----', max_length=100),
            preserve_default=False,
        ),
    ]
